import { Saira } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import StyledComponentsRegistry from "@/lib/registry";
import FilterProvider from "@/context/FilterContext";

const saira = Saira({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={saira.className}>
        <StyledComponentsRegistry>
          <FilterProvider>
            <Header />
            <div className="main_container">{children}</div>
          </FilterProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
