import { Saira } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const saira = Saira({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={saira.className}>
        <Header />
        <div className="main_container">{children}</div>
      </body>
    </html>
  );
}
